services:

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=${HOST}
      - DB_USER=${USER_DB}
      - DB_PASSWORD=${PASSWORD}
      - DB_NAME=${DATABASE}
      - DB_PORT=${PORT}
    depends_on:
      db:
        condition: service_healthy


  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=latte
      - POSTGRES_PASSWORD=latte
      - POSTGRES_DB=frappuccino
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U latte -d frappuccino "]
      interval: 10s
      timeout: 5s
      retries: 5
